spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/study_tracker
    username: furkan
    password: "05542575141"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
